from fastapi import APIRouter
from fastapi.responses import FileResponse
from pydantic import BaseModel
from reportlab.platypus import SimpleDocTemplate, Paragraph, Image, Spacer, HRFlowable
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
import tempfile, os

router = APIRouter(prefix="/pdf", tags=["pdf"])

class PDFRequest(BaseModel):
    text: str


@router.post("/")
async def generate_pdf(data: PDFRequest):
    temp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    doc = SimpleDocTemplate(
        temp.name,
        pagesize=A4,
        leftMargin=2*cm,
        rightMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    normal = styles["Normal"]

    # --- Кастомный стиль текста
    normal.fontName = "Helvetica"
    normal.fontSize = 11
    normal.leading = 15

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=colors.HexColor("#4C1D95"),  # фиолетовый под твою тему
        spaceAfter=12
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        alignment=1,  # по центру
        fontSize=9,
        textColor=colors.gray
    )

    story = []

    # --- Логотип (если есть в static)
    logo_path = "static/logo_pdf.png"
    print(logo_path)
    if os.path.exists(logo_path):
        story.append(Image(logo_path, width=3*cm, height=3*cm))
        story.append(Spacer(1, 0.5*cm))

    # --- Заголовок
    story.append(Paragraph("Text Extraction Result", title_style))
    story.append(HRFlowable(width="100%", color=colors.grey))
    story.append(Spacer(1, 0.5*cm))

    # --- Основной текст
    content = data.text.replace("\n", "<br/>")
    story.append(Paragraph(content, normal))
    story.append(Spacer(1, 1*cm))

    # --- Подвал
    story.append(HRFlowable(width="40%", color=colors.grey))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph("Generated by textract.me", footer_style))

    doc.build(story)

    return FileResponse(
        temp.name,
        media_type="application/pdf",
        filename="result.pdf"
    )
