"""new fix

Revision ID: 4b5f04a6e969
Revises: 
Create Date: 2025-09-25 16:05:12.809915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b5f04a6e969'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('requests', 'from_user')
    op.add_column('users', sa.Column('usage_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usage_reset_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('users', 'tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'usage_reset_at')
    op.drop_column('users', 'usage_count')
    op.add_column('requests', sa.Column('from_user', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'user_id')
    # ### end Alembic commands ###
