"""OCR_link added

Revision ID: c9c44bee258c
Revises: e35a7d19345b
Create Date: 2025-11-13 15:28:51.576899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c44bee258c'
down_revision: Union[str, Sequence[str], None] = 'e35a7d19345b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('pdf_link', sa.String(length=100), nullable=True))
    op.add_column('requests', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'extracted_text')
    op.drop_column('requests', 'pdf_link')
    # ### end Alembic commands ###
