"""empty message

Revision ID: d8a8a8aecbe9
Revises: 66b6fe6e742d
Create Date: 2025-09-22 12:34:15.726169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a8a8aecbe9'
down_revision: Union[str, Sequence[str], None] = '66b6fe6e742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uuid_token')
    # ### end Alembic commands ###
