"""tts_url

Revision ID: e35a7d19345b
Revises: edd2b51e04f5
Create Date: 2025-11-07 13:19:04.278356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35a7d19345b'
down_revision: Union[str, Sequence[str], None] = 'edd2b51e04f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('audio_link', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'audio_link')
    # ### end Alembic commands ###
