"""tts update

Revision ID: edd2b51e04f5
Revises: d7ec57236476
Create Date: 2025-10-30 11:58:20.835095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd2b51e04f5'
down_revision: Union[str, Sequence[str], None] = 'd7ec57236476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('module', sa.String(length=30), nullable=True))
    op.add_column('requests', sa.Column('text_chars', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('audio_duration', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('audio_size', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('voice_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('usage_count_ocr', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tts_usage', sa.Integer(), nullable=True))
    op.drop_column('users', 'usage_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'tts_usage')
    op.drop_column('users', 'usage_count_ocr')
    op.drop_column('requests', 'voice_name')
    op.drop_column('requests', 'audio_size')
    op.drop_column('requests', 'audio_duration')
    op.drop_column('requests', 'text_chars')
    op.drop_column('requests', 'module')
    # ### end Alembic commands ###
